// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebRedis.Domain
{
    public partial class ConnectionConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IpAddress { get; set; }
        public int Port { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public DateTime CreateTime { get; set; }
    }
}